---
version: "3"
services:
  app:
    image: olivere/docker-test-web
  envoy:
    image: envoyproxy/envoy:v1.10.0
    ports:
      - 443:8043
    volumes:
      - ./app.crt:/etc/envoy/certs/app.crt
      - ./app.key:/etc/envoy/certs/app.key
      - ./envoy.yaml:/etc/envoy/envoy.yaml